apiVersion: v1
kind: Secret
metadata:
  name: operator-oauth
  namespace: tailscale
stringData:
  client_id: "{{ .Values.tailscaleAuth.client_id }}"
  client_secret: "{{ .Values.tailscaleAuth.client_secret }}"